### ISSUE TITLE
Is this extension still required in 2020?

### ISSUE THREAD

**Issue by hadrysmateusz** [ChristianKohler/NpmIntellisense#69]
What is the benefit of using this extension in 2020?

Was this functionality added to VS Code natively?

I can't find anything in the patch notes and this extension is still recommended in VSCode docs, but I can't see any difference in the intellisense when this extension is installed.

I'm not sure if I should keep it installed or remove it as it probably slows down VSCode a bit like every other extension.

If it doesn't provide any additional benefit maybe it should be stated on the repository / VSCode marketplace.

**Comment by ChristianKohler** [comment]
From what I know, VS Code has a similar function build in. At least to some extend. Honestly I don't know which features exactly are build in and which would be missing. Would be hard to check and sync that with every release. Closing this issue since the extension is used and downloaded quite often and I don't see any action coming out from this issue.
